ClipShare/Controllers/AdminController.cs
using ClipShare.Core.Entities;
using ClipShare.Utility;
using ClipShare.ViewModels;
using ClipShare.ViewModels.Admin;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClipShare.Controllers
{
    [Authorize(Roles = $"{SD.AdminRole}")]
    public class AdminController : CoreController
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;

        public AdminController(UserManager<AppUser> userManager,
            RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        // ===================== PHẦN 1: USER 3 PHỤ TRÁCH =====================
        // Quản lý user, role, khóa/mở user, xóa user, các chức năng liên quan đến người dùng

        // --- [USER 3] Quản lý danh sách user ---
        public IActionResult Category()
        {
            return View();
        }

        public async Task<IActionResult> AllUsers()
        {
            var toReturn = new List<UserDisplayGrid_vm>();
            var users = await _userManager.Users
                .Include(x => x.Channel)
                .Where(x => x.UserName != "admin")
                .ToListAsync();

            foreach (var user in users)
            {
                var userDisplayToAdd = new UserDisplayGrid_vm();
                Mapper.Map(user, userDisplayToAdd);
                userDisplayToAdd.IsLocked = _userManager.IsLockedOutAsync(user).GetAwaiter().GetResult();
                userDisplayToAdd.AssignedRoles = _userManager.GetRolesAsync(user).GetAwaiter().GetResult();
                toReturn.Add(userDisplayToAdd);
            }

            return View(toReturn);
        }

        // --- [USER 3] Giao diện thêm/sửa user (GET) ---
        public async Task<IActionResult> AddEditUser(int id)
        {
            var toReturn = new UserAddEdit_vm();
            toReturn.ApplicationRoles = await GetApplicationRolesAsync();

            if (id > 0)
            {
                // edit
                var user = await _userManager.FindByIdAsync(id.ToString());
                Mapper.Map(user, toReturn);

                var userRoles = _userManager.GetRolesAsync(user).GetAwaiter().GetResult();
                toReturn.UserRoles = userRoles.ToList();
            }

            return View(toReturn);
        }

        // --- [USER 3] Xử lý thêm/sửa user (POST) ---

        [HttpPost]
        public async Task<IActionResult> AddEditUser(UserAddEdit_vm model)
        {
            if (ModelState.IsValid)
            {
                bool proceed = true;

                if (model.Id == 0)
                {
                    // Creating a user
                    if (string.IsNullOrEmpty(model.Password))
                    {
                        proceed = false;
                        ModelState.AddModelError("Password", "Password is required");
                    }

                    if (proceed && model.UserRoles.Count == 0)
                    {
                        proceed = false;
                        ModelState.AddModelError("UserRoles", "Please select at least one role");
                    }

                    if (proceed && CheckNameExistsAsync(model.Name).GetAwaiter().GetResult())
                    {
                        proceed = false;
                        ModelState.AddModelError("Name", $"The name of '{model.Name} is taken. Please try another name.");
                    }

                    if (proceed && CheckEmailExistsAsync(model.Email).GetAwaiter().GetResult())
                    {
                        proceed = false;
                        ModelState.AddModelError("Email", $"Email address of {model.Email} is taken. Please try using another email address.");
                    }

                    if (proceed)
                    {
                        var userToAdd = new AppUser
                        {
                            Name = model.Name,
                            UserName = model.Name.ToLower(),
                            Email = model.Email,
                        };

                        var result = await _userManager.CreateAsync(userToAdd, model.Password);
                        await _userManager.AddToRolesAsync(userToAdd, model.UserRoles);

                        if (result.Succeeded)
                        {
                            return RedirectToAction("AllUsers");
                        }
                        else
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }
                        }
                    }
                }
                else
                {
                    // Editing an user
                    var user = await _userManager.FindByIdAsync(model.Id.ToString());

                    if (user == null)
                    {
                        TempData["notification"] = "false;Not Found;The requested user was not found";
                        return RedirectToAction("AllUsers");
                    }

                    if (IsSuperAdminUserId(model.Id))
                    {
                        TempData["notification"] = "false;Bad Request;Super Admin change is not allowed!";
                        return RedirectToAction("AllUsers");
                    }

                    if (model.UserRoles.Count == 0)
                    {
                        proceed = false;
                        ModelState.AddModelError("UserRoles", "Please select at least one role");
                    }

                    if (proceed && !user.Name.Equals(model.Name))
                    {
                        if (CheckNameExistsAsync(model.Name).GetAwaiter().GetResult())
                        {
                            proceed = false;
                            ModelState.AddModelError("Name", $"The name of '{model.Name} is taken. Please try another name.");
                        }
                    }

                    if (proceed && !user.Email.Equals(model.Email))
                    {
                        if (CheckEmailExistsAsync(model.Email).GetAwaiter().GetResult())
                        {
                            proceed = false;
                            ModelState.AddModelError("Email", $"Email address of {model.Email} is taken. Please try using another email address.");
                        }
                    }

                    if (proceed && !string.IsNullOrEmpty(model.Password))
                    {
                        // Changing the user's password
                        await _userManager.RemovePasswordAsync(user);
                        var result = await _userManager.AddPasswordAsync(user, model.Password);

                        if (!result.Succeeded)
                        {
                            proceed = false;
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError(string.Empty, error.Description);
                            }
                        }
                    }

                    if (proceed)
                    {
                        user.Name = model.Name;
                        user.UserName = model.Name.ToLower();
                        user.Email = model.Email;

                        var userRoles = await _userManager.GetRolesAsync(user);
                        // remove user's existing roles
                        await _userManager.RemoveFromRolesAsync(user, userRoles);

                        // adding the new roles
                        foreach (var role in model.UserRoles)
                        {
                            var roleToAdd = await _roleManager.Roles.FirstOrDefaultAsync(r => r.Name == role);
                            if (roleToAdd != null)
                            {
                                await _userManager.AddToRoleAsync(user, role);
                            }
                        }

                        return RedirectToAction("AllUsers");
                    }
                }
            }

            model.ApplicationRoles = await GetApplicationRolesAsync();
            return View(model);
        }

        // --- [USER 3] Khóa user ---

        [HttpPost]
        public async Task<IActionResult> LockUser(int id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());

            if (user == null)
            {
                TempData["notification"] = "false;Not Found;The requested user was not found";
                return RedirectToAction("AllUsers");
            }

            if (IsSuperAdminUserId(id))
            {
                TempData["notification"] = "false;Bad Request;Super Admin change is not allowed!";
                return RedirectToAction("AllUsers");
            }

            // Lock the user for 5 days
            user.LockoutEnabled = true;
            var result = await _userManager.SetLockoutEndDateAsync(user, DateTime.UtcNow.AddDays(5));

            if (!result.Succeeded)
            {
                TempData["notification"] = "false;Server Error;Server Error";
            }

            return RedirectToAction("AllUsers");
        }

        // --- [USER 3] Mở khóa user ---

        [HttpPost]
        public async Task<IActionResult> UnlockUser(int id)
        {
            var user = await _userManager.FindByIdAsync(id.ToString());

            if (user == null)
            {
                TempData["notification"] = "false;Not Found;The requested user was not found";

ClipShare/Controllers/ModeratorController.cs
using ClipShare.Utility;
using ClipShare.ViewModels.Moderator;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClipShare.Controllers
{
    [Authorize(Roles = $"{SD.ModeratorRole}")]
    public class ModeratorController : CoreController
    {
        public async Task<IActionResult> AllVideos()
        {
            var videos = await UnitOfWork.VideoRepo.GetAllAsync(includeProperties: "Category,Channel");

            var toReturn = Mapper.Map<IEnumerable<VideoDisplayGrid_vm>>(videos);

            return View(toReturn);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteVideo(int id)
        {
            var video = await Context.Video
                .Where(x => x.Id == id)
                .Select(x => new
                {
                    x.Id,
                    x.ThumbnailUrl,
                    x.Title
                }).FirstOrDefaultAsync();

            if (video != null)
            {
                PhotoService.DeletePhotoLocally(video.ThumbnailUrl);
                await UnitOfWork.VideoRepo.RemoveVideoAsync(video.Id);
                await UnitOfWork.CompleteAsync();

                TempData["notification"] = $"true;Deleted;Video of {video.Title} has been deleted";
                return RedirectToAction("AllVideos");
            }

            TempData["notification"] = $"false;Not Found;Requested video was not found";
            return RedirectToAction("AllVideos");
        }
    }
}

ClipShare/Views/Shared/_Confirmation.cshtml
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id="confirmationModalContent" class="modal-content">
        </div>
    </div>
</div>

<button type="button" id="confirmModalButton" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmationModal" style="display:none">
    Launch demo modal
</button>


<script>
    function confirmation(message) {
        return new Promise((resolve) => {
            $('#confirmationModalContent').empty();

            var modalContentInnerHtml =
                `
                    <div class="modal-header bg-info">
                        <h5 class="modal-title text-white" id="modalLabel">Confirmation</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        ${message}
                    </div>
                    <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-bs-dismiss="modal" id="confirmOk">OK</button>
                            <button type="button" class="btn btn-danger" data-bs-dismiss="modal" id="confirmCancel">Cancel</button>
                    </div>`;

            $("#confirmationModalContent").append(modalContentInnerHtml);
            $("#confirmModalButton").trigger('click');

            $('#confirmOk').on('click', function () {
                resolve(true);
            });

            $('#confirmCancel').on('click', function () {
                resolve(false);
            });
        });
    }
</script>

ClipShare/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClipShare</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" integrity="sha512-vKMx8UnXk60zUwyUnUPM3HbQo8QfmNx7+ltw8Pm5zLusl1XIfwcxo8DbWCqMGKaWeNxWA8yrx5v3SaVpMvR3CA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ClipShare.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-lg navbar-light bg-primary border-bottom box-shadow mb-3" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ClipShare</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-lg-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white @Html.IsActive("Home", "Index")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (_signInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole(SD.AdminRole))
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Admin" asp-action="PendingVideos">Pending Videos</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle text-white" href="#" id="adminDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Administration
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="adminDropdown">
                                        <li><a class="dropdown-item" asp-controller="Admin" asp-action="Category">Category</a></li>
                                        <li><a class="dropdown-item" asp-controller="Admin" asp-action="AllUsers">All Users</a></li>
                                    </ul>
                                </li>
                                <!-- Additional admin links can be added here -->
                            }

                            @if (User.IsInRole(SD.ModeratorRole))
                            {
                                <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle text-white" href="#" id="moderatorDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        Moderator
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="moderatorDropdown">
                                        <li><a class="dropdown-item" asp-controller="Moderator" asp-action="AllVideos">All Videos</a></li>
                                    </ul>
                                </li>
                            }
                        }

                    </ul>
                    <partial name="_LoginPartial" />

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="main pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; @DateTime.Now.Year - <a asp-area="" asp-controller="Home" asp-action="Index">ClipShare</a>
        </div>
    </footer>

    <partial name="_Notification" />
    <partial name="_Confirmation" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/2.1.8/js/dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ClipShare/Views/Shared/_Notification.cshtml
<div class="modal fade" id="notificationModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id="notificationModalContent" class="modal-content">
        </div>
    </div>
</div>

<button type="button" id="triggerModalButton" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#notificationModal" style="display:none;">
    Launch demo modal
</button>


@if (TempData["notification"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script>
        $(function () {
            const notificationModel = '@TempData["notification"]'.split(";");
            let isSuccess = (notificationModel[0] === 'true');
            let title = notificationModel[1];
            let message = notificationModel[2];
            let type = notificationModel[3];

            displayNotification(isSuccess, title, message, type);
        });
    </script>
}

<script>
    function displayNotification(isSuccess, title, message, type = 'modal') {
        $('#notificationModalContent').empty();

        if (type == 'modal') {
            var modalContentInnerHtml =
                `
                <div class="modal-header ${isSuccess === true ? 'bg-success' : 'bg-danger'}">
                    <h5 class="modal-title" id="modalLabel">${title}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    ${message}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-bs-dismiss="modal">OK</button>
                </div>`;

            $("#notificationModalContent").append(modalContentInnerHtml);
            $("#triggerModalButton").trigger('click');
        } else {
            toastr.options = {
                positionClass: "toast-bottom-right"
            };

            if (isSuccess) {
                toastr.success(message);
            } else {
                toastr.error(message);
            }
        }
    }
</script>